# slot=sprite, after folding identical patches onto one file
ov_cover.0=ov_cover_0
ov_cover.1=ov_cover_0
ov_cover.2=ov_cover_2
ov_cover.3=ov_cover_3
ov_cover.4=ov_cover_4
ov_cover.5=ov_cover_5
ov_cover.6=ov_cover_6
ov_cover.7=ov_cover_0
ov_cover.8=ov_cover_0
ov_cover.9=ov_cover_0
ov_cover.10=ov_cover_10
ov_cover.11=ov_cover_10
ov_cover.12=ov_cover_10
ov_cover.13=ov_cover_10
ov_cover.14=ov_cover_10
ov_cover.15=ov_cover_10
ov_cover.16=ov_cover_10
ov_cover.17=ov_cover_0
ov_cover.18=ov_cover_0
ov_cover.19=ov_cover_10
ov_cover.20=ov_cover_10
ov_cover.21=ov_cover_10
ov_cover.22=ov_cover_10
ov_cover.23=ov_cover_10
ov_cover.24=ov_cover_10
ov_cover.25=ov_cover_10
ov_cover.26=ov_cover_0
ov_cover.27=ov_cover_0
ov_cover.28=ov_cover_28
ov_cover.29=ov_cover_29
ov_cover.30=ov_cover_30
ov_cover.31=ov_cover_31
ov_cover.32=ov_cover_32
ov_cover.33=ov_cover_33
ov_cover.34=ov_cover_34
ov_cover.35=ov_cover_0
ov_cover.36=ov_cover_0
ov_cover.37=ov_cover_0
ov_cover.38=ov_cover_0
ov_cover.39=ov_cover_39
ov_cover.40=ov_cover_40
ov_cover.41=ov_cover_41
ov_cover.42=ov_cover_0
ov_cover.43=ov_cover_0
ov_cover.44=ov_cover_0
ov_cover.45=ov_cover_0
ov_cover.46=ov_cover_10
ov_cover.47=ov_cover_10
ov_cover.48=ov_cover_10
ov_cover.49=ov_cover_10
ov_cover.50=ov_cover_10
ov_cover.51=ov_cover_10
ov_cover.52=ov_cover_10
ov_cover.53=ov_cover_0
ov_hover.0=ov_hover_0
ov_hover.1=ov_hover_0
ov_hover.2=ov_hover_2
ov_hover.3=ov_hover_3
ov_hover.4=ov_hover_4
ov_hover.5=ov_hover_5
ov_hover.6=ov_hover_6
ov_hover.7=ov_hover_0
ov_hover.8=ov_hover_0
ov_hover.9=ov_hover_0
ov_hover.10=ov_hover_10
ov_hover.11=ov_hover_10
ov_hover.12=ov_hover_10
ov_hover.13=ov_hover_10
ov_hover.14=ov_hover_10
ov_hover.15=ov_hover_10
ov_hover.16=ov_hover_10
ov_hover.17=ov_hover_0
ov_hover.18=ov_hover_0
ov_hover.19=ov_hover_10
ov_hover.20=ov_hover_10
ov_hover.21=ov_hover_10
ov_hover.22=ov_hover_10
ov_hover.23=ov_hover_10
ov_hover.24=ov_hover_10
ov_hover.25=ov_hover_10
ov_hover.26=ov_hover_0
ov_hover.27=ov_hover_0
ov_hover.28=ov_hover_28
ov_hover.29=ov_hover_29
ov_hover.30=ov_hover_30
ov_hover.31=ov_hover_31
ov_hover.32=ov_hover_32
ov_hover.33=ov_hover_33
ov_hover.34=ov_hover_34
ov_hover.35=ov_hover_0
ov_hover.36=ov_hover_0
ov_hover.37=ov_hover_0
ov_hover.38=ov_hover_0
ov_hover.39=ov_hover_39
ov_hover.40=ov_hover_40
ov_hover.41=ov_hover_41
ov_hover.42=ov_hover_0
ov_hover.43=ov_hover_0
ov_hover.44=ov_hover_0
ov_hover.45=ov_hover_0
ov_hover.46=ov_hover_10
ov_hover.47=ov_hover_10
ov_hover.48=ov_hover_10
ov_hover.49=ov_hover_10
ov_hover.50=ov_hover_10
ov_hover.51=ov_hover_10
ov_hover.52=ov_hover_10
ov_hover.53=ov_hover_0
